@hostname=localhost
@port=5002

POST https://{{hostname}}:{{port}}/api/workflows/create
Content-Type: application/json

{
    "companyId": 1,
    "workflowTemplateId": 1,
    "requestData": { 
      "Employee": { 
        "Name": "Alice Smith", 
        "Email": "alice.smith@acme.com" 
      },
      "Date": "2024-08-08T13:35:11.857Z"
    }
}

###

POST https://{{hostname}}:{{port}}/api/workflows/start
Content-Type: application/json

{
    "companyId": 1,
    "workflowRequestId": "3ac2245a-85a1-4c8e-82f7-a71fb14b5886"
}