@hostname=localhost
@port=5002

POST https://{{hostname}}:{{port}}/api/workflows/create
Content-Type: application/json

{
    "companyId": 1,
    "workflowTemplateId": 1,
    "requestData": {
      "request": {
        "reason": "Vacation",  
        "startDate": "2024-08-09",
	      "endDate": "2024-09-02",
        "type": "Full Day",
        "traveledDays": 2  
      }
    }
}

###

POST https://{{hostname}}:{{port}}/api/workflows/submit
Content-Type: application/json

{
    "companyId": 1,
    "workflowRequestId": "1d141479-1eae-4393-8c8d-96f854359e8c"
}