@hostname=localhost
@port=5002

# @name createRequest
###
POST https://{{hostname}}:{{port}}/api/workflows/create
Content-Type: application/json

{
    "workflowDefinitionId": "cfcf05b58c9c29b5"
}

###
POST https://{{hostname}}:{{port}}/api/workflows/submit
Content-Type: application/json

{
    "workflowRequestId": {{createRequest.response.body.*}}
}